[unpack]
blacklist = [
    "application/json",
    "application/pdf",
    "application/x-java-applet",
    "application/x-object",
    "application/x-sharedlib",
    "application/x-shockwave-flash",
    "application/x-terminfo",
    "audio/mpeg",
    "font/sfnt",
    "image/bmp",
    "image/gif",
    "image/jpeg",
    "image/png",
    "image/x-tga",
    "image/x-win-bitmap",
    "inode/symlink",
    "text/csv",
    "text/plain",
    "video/mp4",
    "video/mpeg",
    "video/ogg",
    "video/quicktime",
    "video/x-msvideo",
]
data_folder = "/tmp/extractor"
exclude = []

[expert_settings]
statistics = true
unpack_threshold = 0.8
header_overhead = 256
compressed_file_types = [
    "application/x-shockwave-flash",
    "audio/mpeg",
    "audio/ogg",
    "image/gif",
    "image/jpeg",
    "image/png",
    "video/mp4",
    "video/ogg",
]
